kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30545    # Anvil NodePort
        hostPort: 8545
        protocol: TCP
      - containerPort: 30400    # eRPC NodePort
        hostPort: 4000
        protocol: TCP
      - containerPort: 30123    # ClickHouse HTTP NodePort
        hostPort: 8123
        protocol: TCP
      - containerPort: 31808    # rindexer metrics NodePort
        hostPort: 18080
        protocol: TCP
      - containerPort: 30300    # Grafana NodePort (optional)
        hostPort: 3000
        protocol: TCP
