# Generated by evm-cloud v0.0.1-alpha8 builder
# https://app.evm-cloud.xyz
# Regenerate with the builder or use `evm-cloud init` to modify

# ======================================================================
# Core
# ======================================================================

variable "project_name" {
  description = "Name of the deployment project"
  type = string
}

variable "infrastructure_provider" {
  description = "Cloud provider: aws or bare_metal"
  type = string
}

variable "database_mode" {
  description = "Database deployment: managed or self_hosted"
  type = string
}

variable "compute_engine" {
  description = "Compute engine: ec2, eks, k3s, or docker_compose"
  type = string
}

variable "workload_mode" {
  description = "Workload management: terraform or external"
  type = string
}

variable "secrets_mode" {
  description = "Secrets management: inline, provider, or external"
  type = string
}

variable "ingress_mode" {
  description = "Ingress type: none, cloudflare, caddy, or ingress_nginx"
  type = string
}

variable "erpc_hostname" {
  description = "Hostname for eRPC proxy endpoint"
  type    = string
  default = ""
}

variable "ingress_tls_email" {
  description = "Email for Let's Encrypt certificate provisioning"
  type    = string
  default = ""
}

variable "deployment_target" {
  description = "Deployment target"
  type    = string
  default = "managed"
}

variable "runtime_arch" {
  description = "Runtime architecture: amd64, arm64, or multi"
  type    = string
  default = "multi"
}

variable "streaming_mode" {
  description = "Event streaming: disabled, kafka, sns-sqs, or cdc"
  type    = string
  default = "disabled"
}


# ======================================================================
# SSH
# ======================================================================

variable "ssh_private_key_path" {
  description = "Path to SSH private key for provisioner"
  type      = string
  default   = ""
  sensitive = true
}


# ======================================================================
# AWS
# ======================================================================

variable "networking_enabled" {
  description = "Enable VPC and networking resources"
  type = bool
}

variable "aws_region" {
  description = "AWS region for all resources"
  type = string
}

variable "ssh_public_key" {
  description = "SSH public key for EC2 instances"
  type      = string
  sensitive = true
}

variable "network_availability_zones" {
  description = "Availability zones for subnets"
  type = list(string)
}

variable "network_enable_nat_gateway" {
  description = "Enable NAT gateway for private subnets"
  type = bool
}

variable "network_environment" {
  description = "Environment tag (dev, staging, production)"
  type    = string
  default = "dev"
}

variable "network_vpc_cidr" {
  description = "VPC CIDR block"
  type    = string
  default = "10.42.0.0/16"
}

variable "network_enable_vpc_endpoints" {
  description = "Enable VPC endpoints for AWS services"
  type    = bool
  default = false
}


# ======================================================================
# Compute
# ======================================================================

variable "ec2_instance_type" {
  description = "EC2 instance type"
  type = string
}

variable "ec2_rpc_proxy_mem_limit" {
  description = "Memory limit for eRPC on EC2"
  type    = string
  default = "1g"
}

variable "ec2_indexer_mem_limit" {
  description = "Memory limit for indexer on EC2"
  type    = string
  default = "2g"
}

variable "ec2_secret_recovery_window_in_days" {
  description = "Secrets Manager recovery window (days)"
  type    = number
  default = 7
}


# ======================================================================
# Indexer
# ======================================================================

variable "rpc_proxy_enabled" {
  description = "Enable eRPC proxy deployment"
  type = bool
}

variable "indexer_enabled" {
  description = "Enable rindexer deployment"
  type = bool
}

variable "indexer_rpc_url" {
  description = "RPC endpoint URL for indexer"
  type    = string
  default = ""
}

variable "indexer_storage_backend" {
  description = "Storage backend: clickhouse or postgres"
  type = string
}

variable "rpc_proxy_image" {
  description = "Docker image for eRPC"
  type    = string
  default = "ghcr.io/erpc/erpc:latest"
}

variable "indexer_image" {
  description = "Docker image for rindexer"
  type    = string
  default = "ghcr.io/joshstevens19/rindexer:latest"
}

variable "erpc_config_yaml" {
  description = "eRPC configuration YAML content"
  type    = string
  default = ""
}

variable "rindexer_config_yaml" {
  description = "rindexer configuration YAML content"
  type    = string
  default = ""
}

variable "rindexer_abis" {
  description = "ABI files: { filename = content }"
  type    = map(string)
  default = {}
}

variable "indexer_extra_env" {
  description = "Extra environment variables for indexer"
  type    = map(string)
  default = {}
}

variable "indexer_extra_secret_env" {
  description = "Extra sensitive environment variables for indexer"
  type      = map(string)
  default   = {}
  sensitive = true
}

variable "postgres_enabled" {
  description = "Enable PostgreSQL"
  type = bool
}

variable "postgres_instance_class" {
  description = "RDS instance class"
  type    = string
  default = "db.t4g.micro"
}

variable "postgres_engine_version" {
  description = "PostgreSQL engine version"
  type    = string
  default = "16.4"
}

variable "postgres_db_name" {
  description = "Database name"
  type    = string
  default = "rindexer"
}

variable "postgres_db_username" {
  description = "Database username"
  type    = string
  default = "rindexer"
}

variable "postgres_backup_retention" {
  description = "Backup retention (days)"
  type    = number
  default = 7
}

variable "postgres_manage_master_user_password" {
  description = "Let RDS manage the master password"
  type    = bool
  default = true
}

variable "postgres_master_password" {
  description = "Master password (only if manage_master_user_password = false)"
  type      = string
  default   = null
  sensitive = true
}

variable "postgres_force_ssl" {
  description = "Enforce SSL for PostgreSQL connections"
  type    = bool
  default = false
}


# ======================================================================
# Secrets
# ======================================================================

variable "secrets_manager_secret_arn" {
  description = "AWS Secrets Manager ARN"
  type      = string
  default   = ""
  sensitive = true
}

variable "secrets_manager_kms_key_id" {
  description = "AWS KMS key ID for encryption"
  type    = string
  default = ""
}

variable "eso_chart_version" {
  description = "External Secrets Operator Helm chart version"
  type    = string
  default = "0.9.13"
}
