# Generated by evm-cloud v0.0.1-alpha8 builder
# https://app.evm-cloud.xyz
# Regenerate with the builder or use `evm-cloud init` to modify

terraform {
  required_version = ">= 1.5"

  required_providers {
  }
}
