# Generated by evm-cloud v0.0.1-alpha8 builder
# https://app.evm-cloud.xyz
# Regenerate with the builder or use `evm-cloud init` to modify

module "evm_cloud" {
  source = "github.com/exomonk/evm-cloud?ref=v0.0.1-alpha8"

  # --- Core ---
  project_name            = var.project_name
  infrastructure_provider = var.infrastructure_provider
  database_mode           = var.database_mode
  compute_engine          = var.compute_engine
  workload_mode           = var.workload_mode
  secrets_mode            = var.secrets_mode
  ingress_mode            = var.ingress_mode
  erpc_hostname           = var.erpc_hostname
  ingress_tls_email       = var.ingress_tls_email
  deployment_target       = var.deployment_target
  runtime_arch            = var.runtime_arch
  streaming_mode          = var.streaming_mode

  # --- SSH ---
  ssh_private_key_path = var.ssh_private_key_path

  # --- AWS ---
  networking_enabled           = var.networking_enabled
  aws_region                   = var.aws_region
  ssh_public_key               = var.ssh_public_key
  network_availability_zones   = var.network_availability_zones
  network_enable_nat_gateway   = var.network_enable_nat_gateway
  network_environment          = var.network_environment
  network_vpc_cidr             = var.network_vpc_cidr
  network_enable_vpc_endpoints = var.network_enable_vpc_endpoints
  k3s_version                  = var.k3s_version

  # --- Indexer ---
  rpc_proxy_enabled                    = var.rpc_proxy_enabled
  indexer_enabled                      = var.indexer_enabled
  indexer_rpc_url                      = var.indexer_rpc_url
  indexer_storage_backend              = var.indexer_storage_backend
  rpc_proxy_image                      = var.rpc_proxy_image
  indexer_image                        = var.indexer_image
  erpc_config_yaml                     = var.erpc_config_yaml
  rindexer_config_yaml                 = var.rindexer_config_yaml
  rindexer_abis                        = var.rindexer_abis
  indexer_extra_env                    = var.indexer_extra_env
  indexer_extra_secret_env             = var.indexer_extra_secret_env
  postgres_enabled                     = var.postgres_enabled
  postgres_instance_class              = var.postgres_instance_class
  postgres_engine_version              = var.postgres_engine_version
  postgres_db_name                     = var.postgres_db_name
  postgres_db_username                 = var.postgres_db_username
  postgres_backup_retention            = var.postgres_backup_retention
  postgres_manage_master_user_password = var.postgres_manage_master_user_password
  postgres_master_password             = var.postgres_master_password
  postgres_force_ssl                   = var.postgres_force_ssl
  ingress_nginx_chart_version          = var.ingress_nginx_chart_version
  ingress_cert_manager_chart_version   = var.ingress_cert_manager_chart_version
  ingress_request_body_max_size        = var.ingress_request_body_max_size
  ingress_tls_staging                  = var.ingress_tls_staging
  ingress_hsts_preload                 = var.ingress_hsts_preload
  ingress_class_name                   = var.ingress_class_name

  # --- Secrets ---
  secrets_manager_secret_arn = var.secrets_manager_secret_arn
  secrets_manager_kms_key_id = var.secrets_manager_kms_key_id
  eso_chart_version          = var.eso_chart_version

  # --- Monitoring ---
  monitoring_enabled            = var.monitoring_enabled
  kube_prometheus_stack_version = var.kube_prometheus_stack_version
  grafana_ingress_enabled       = var.grafana_ingress_enabled
  grafana_hostname              = var.grafana_hostname
  alertmanager_route_target     = var.alertmanager_route_target
  alertmanager_slack_channel    = var.alertmanager_slack_channel
  loki_enabled                  = var.loki_enabled
  loki_chart_version            = var.loki_chart_version
  clickhouse_metrics_url        = var.clickhouse_metrics_url
}
