# Generated by evm-cloud v0.0.1-alpha8 builder
# https://app.evm-cloud.xyz
# Regenerate with the builder or use `evm-cloud init` to modify


# ──────────────────────────────────────────────────────────────────────
# Core
# ──────────────────────────────────────────────────────────────────────

project_name            = "golden-test"
infrastructure_provider = "aws"
compute_engine          = "eks"
workload_mode           = "external"
database_mode           = "managed"
secrets_mode            = "provider"
deployment_target       = "managed"
runtime_arch            = "multi"

# ──────────────────────────────────────────────────────────────────────
# AWS Networking
# ──────────────────────────────────────────────────────────────────────

networking_enabled           = true
aws_region                   = "us-east-1"
network_availability_zones   = ["us-east-1a", "us-east-1b"]
network_enable_nat_gateway   = false
network_environment          = "dev"
network_vpc_cidr             = "10.42.0.0/16"
network_enable_vpc_endpoints = false

# ──────────────────────────────────────────────────────────────────────
# Database
# ──────────────────────────────────────────────────────────────────────

indexer_storage_backend = "postgres"
postgres_enabled        = true

# ──────────────────────────────────────────────────────────────────────
# Indexer / RPC Proxy
# ──────────────────────────────────────────────────────────────────────

rpc_proxy_enabled = true
indexer_enabled   = true
indexer_rpc_url   = ""
rpc_proxy_image   = "ghcr.io/erpc/erpc:latest"
indexer_image     = "ghcr.io/joshstevens19/rindexer:latest"

# Config content — populated by `evm-cloud init` from config/ files
erpc_config_yaml     = ""
rindexer_config_yaml = ""
rindexer_abis        = {}
indexer_extra_env    = {}

# ──────────────────────────────────────────────────────────────────────
# Ingress
# ──────────────────────────────────────────────────────────────────────

ingress_mode      = "ingress_nginx"
erpc_hostname     = "rpc.example.com"
ingress_tls_email = "admin@example.com"

# ──────────────────────────────────────────────────────────────────────
# Streaming
# ──────────────────────────────────────────────────────────────────────

streaming_mode = "disabled"

# ──────────────────────────────────────────────────────────────────────
# Monitoring
# ──────────────────────────────────────────────────────────────────────

monitoring_enabled = true
grafana_hostname   = "grafana.example.com"
loki_enabled       = true