# Generated by evm-cloud v0.0.1-alpha8 builder
# https://app.evm-cloud.xyz
# Regenerate with the builder or use `evm-cloud init` to modify

# ======================================================================
# Core
# ======================================================================

variable "project_name" {
  description = "Name of the deployment project"
  type        = string
}

variable "infrastructure_provider" {
  description = "Cloud provider: aws or bare_metal"
  type        = string
}

variable "database_mode" {
  description = "Database deployment: managed or self_hosted"
  type        = string
}

variable "compute_engine" {
  description = "Compute engine: ec2, eks, k3s, or docker_compose"
  type        = string
}

variable "workload_mode" {
  description = "Workload management: terraform or external"
  type        = string
}

variable "secrets_mode" {
  description = "Secrets management: inline, provider, or external"
  type        = string
}

variable "ingress_mode" {
  description = "Ingress type: none, cloudflare, caddy, or ingress_nginx"
  type        = string
}

variable "erpc_hostname" {
  description = "Hostname for eRPC proxy endpoint"
  type        = string
  default     = ""
}

variable "ingress_tls_email" {
  description = "Email for Let's Encrypt certificate provisioning"
  type        = string
  default     = ""
}

variable "deployment_target" {
  description = "Deployment target"
  type        = string
  default     = "managed"
}

variable "runtime_arch" {
  description = "Runtime architecture: amd64, arm64, or multi"
  type        = string
  default     = "multi"
}

variable "streaming_mode" {
  description = "Event streaming: disabled, kafka, sns-sqs, or cdc"
  type        = string
  default     = "disabled"
}


# ======================================================================
# SSH
# ======================================================================

variable "ssh_private_key_path" {
  description = "Path to SSH private key for provisioner"
  type        = string
  default     = ""
  sensitive   = true
}


# ======================================================================
# AWS
# ======================================================================

variable "networking_enabled" {
  description = "Enable VPC and networking resources"
  type        = bool
}

variable "aws_region" {
  description = "AWS region for all resources"
  type        = string
}

variable "ssh_public_key" {
  description = "SSH public key for EC2 instances"
  type        = string
  sensitive   = true
}

variable "network_availability_zones" {
  description = "Availability zones for subnets"
  type        = list(string)
}

variable "network_enable_nat_gateway" {
  description = "Enable NAT gateway for private subnets"
  type        = bool
}

variable "network_environment" {
  description = "Environment tag (dev, staging, production)"
  type        = string
  default     = "dev"
}

variable "network_vpc_cidr" {
  description = "VPC CIDR block"
  type        = string
  default     = "10.42.0.0/16"
}

variable "network_enable_vpc_endpoints" {
  description = "Enable VPC endpoints for AWS services"
  type        = bool
  default     = false
}

variable "k3s_version" {
  description = "k3s release version"
  type        = string
  default     = "v1.30.4+k3s1"
}


# ======================================================================
# Indexer
# ======================================================================

variable "rpc_proxy_enabled" {
  description = "Enable eRPC proxy deployment"
  type        = bool
}

variable "indexer_enabled" {
  description = "Enable rindexer deployment"
  type        = bool
}

variable "indexer_rpc_url" {
  description = "RPC endpoint URL for indexer"
  type        = string
  default     = ""
}

variable "indexer_storage_backend" {
  description = "Storage backend: clickhouse or postgres"
  type        = string
}

variable "rpc_proxy_image" {
  description = "Docker image for eRPC"
  type        = string
  default     = "ghcr.io/erpc/erpc:latest"
}

variable "indexer_image" {
  description = "Docker image for rindexer"
  type        = string
  default     = "ghcr.io/joshstevens19/rindexer:latest"
}

variable "erpc_config_yaml" {
  description = "eRPC configuration YAML content"
  type        = string
  default     = ""
}

variable "rindexer_config_yaml" {
  description = "rindexer configuration YAML content"
  type        = string
  default     = ""
}

variable "rindexer_abis" {
  description = "ABI files: { filename = content }"
  type        = map(string)
  default     = {}
}

variable "indexer_extra_env" {
  description = "Extra environment variables for indexer"
  type        = map(string)
  default     = {}
}

variable "indexer_extra_secret_env" {
  description = "Extra sensitive environment variables for indexer"
  type        = map(string)
  default     = {}
  sensitive   = true
}

variable "postgres_enabled" {
  description = "Enable PostgreSQL"
  type        = bool
}

variable "postgres_instance_class" {
  description = "RDS instance class"
  type        = string
  default     = "db.t4g.micro"
}

variable "postgres_engine_version" {
  description = "PostgreSQL engine version"
  type        = string
  default     = "16.4"
}

variable "postgres_db_name" {
  description = "Database name"
  type        = string
  default     = "rindexer"
}

variable "postgres_db_username" {
  description = "Database username"
  type        = string
  default     = "rindexer"
}

variable "postgres_backup_retention" {
  description = "Backup retention (days)"
  type        = number
  default     = 7
}

variable "postgres_manage_master_user_password" {
  description = "Let RDS manage the master password"
  type        = bool
  default     = true
}

variable "postgres_master_password" {
  description = "Master password (only if manage_master_user_password = false)"
  type        = string
  default     = null
  sensitive   = true
}

variable "postgres_force_ssl" {
  description = "Enforce SSL for PostgreSQL connections"
  type        = bool
  default     = false
}

variable "ingress_nginx_chart_version" {
  description = "ingress-nginx Helm chart version"
  type        = string
  default     = "4.11.3"
}

variable "ingress_cert_manager_chart_version" {
  description = "cert-manager Helm chart version"
  type        = string
  default     = "1.16.2"
}

variable "ingress_request_body_max_size" {
  description = "Maximum request body size"
  type        = string
  default     = "1m"
}

variable "ingress_tls_staging" {
  description = "Use Let's Encrypt staging (avoid rate limits during testing)"
  type        = bool
  default     = false
}

variable "ingress_hsts_preload" {
  description = "Enable HSTS preload"
  type        = bool
  default     = false
}

variable "ingress_class_name" {
  description = "Kubernetes ingress class name"
  type        = string
  default     = "nginx"
}


# ======================================================================
# Secrets
# ======================================================================

variable "secrets_manager_secret_arn" {
  description = "AWS Secrets Manager ARN"
  type        = string
  default     = ""
  sensitive   = true
}

variable "secrets_manager_kms_key_id" {
  description = "AWS KMS key ID for encryption"
  type        = string
  default     = ""
}

variable "eso_chart_version" {
  description = "External Secrets Operator Helm chart version"
  type        = string
  default     = "0.9.13"
}


# ======================================================================
# Monitoring
# ======================================================================

variable "monitoring_enabled" {
  description = "Enable Grafana + Prometheus monitoring stack"
  type        = bool
  default     = false
}

variable "kube_prometheus_stack_version" {
  description = "kube-prometheus-stack Helm chart version"
  type        = string
  default     = "72.6.2"
}

variable "grafana_ingress_enabled" {
  description = "Expose Grafana via ingress"
  type        = bool
  default     = true
}

variable "grafana_hostname" {
  description = "Grafana hostname for ingress"
  type        = string
  default     = ""
}

variable "alertmanager_route_target" {
  description = "Alert routing target: slack, sns, pagerduty"
  type        = string
  default     = "slack"
}

variable "alertmanager_slack_channel" {
  description = "Slack channel for alerts"
  type        = string
  default     = "#alerts"
}

variable "loki_enabled" {
  description = "Enable Loki log aggregation"
  type        = bool
  default     = false
}

variable "loki_chart_version" {
  description = "Loki Helm chart version"
  type        = string
  default     = "6.24.0"
}

variable "clickhouse_metrics_url" {
  description = "ClickHouse metrics endpoint for Grafana"
  type        = string
  default     = ""
}
