use std::fs;
use std::path::Path;

use sha2::{Digest, Sha256};

fn main() {
    let scripts = [
        ("K3S_DEPLOY_SHA256", "../deployers/k3s/deploy.sh"),
        ("K3S_TEARDOWN_SHA256", "../deployers/k3s/teardown.sh"),
        (
            "K3S_RENDER_VALUES_SHA256",
            "../deployers/k3s/scripts/render-values.sh",
        ),
        (
            "EKS_POPULATE_VALUES_SHA256",
            "../deployers/eks/scripts/populate-values-from-config-bundle.sh",
        ),
        ("COMPOSE_DEPLOY_SHA256", "../deployers/compose/deploy.sh"),
    ];

    let chart_root = Path::new("../deployers/charts");
    println!("cargo:rerun-if-changed={}", chart_root.display());

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs\n");

    for (const_name, rel_path) in scripts {
        println!("cargo:rerun-if-changed={rel_path}");

        let content =
            fs::read(rel_path).unwrap_or_else(|err| panic!("failed to read {rel_path}: {err}"));
        let digest = Sha256::digest(content);
        generated.push_str(&format!("const {const_name}: &str = \"{digest:x}\";\n"));
    }

    let chart_files = collect_files(chart_root);
    generated.push_str("const CHART_ASSETS: &[(&str, &str)] = &[\n");
    for file in chart_files {
        let rel = file
            .strip_prefix("../deployers/")
            .expect("chart file under ../deployers");
        let rel_display = rel.to_string_lossy().replace('\\', "/");
        println!("cargo:rerun-if-changed={}", file.display());
        let abs = fs::canonicalize(&file)
            .unwrap_or_else(|err| panic!("failed to canonicalize {}: {err}", file.display()));
        let abs_lit = abs.to_string_lossy().replace('\\', "\\\\");
        generated.push_str(&format!(
            "    ({rel_display:?}, include_str!({abs_lit:?})),\n"
        ));
    }
    generated.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
    let out_file = Path::new(&out_dir).join("script_checksums.rs");
    fs::write(out_file, generated).expect("write generated checksum constants");
}

fn collect_files(root: &Path) -> Vec<std::path::PathBuf> {
    let mut acc = Vec::new();
    walk(root, &mut acc);
    acc.sort();
    acc
}

fn walk(path: &Path, acc: &mut Vec<std::path::PathBuf>) {
    let entries = fs::read_dir(path)
        .unwrap_or_else(|err| panic!("failed to read dir {}: {err}", path.display()));

    for entry in entries {
        let entry = entry.unwrap_or_else(|err| panic!("failed to read dir entry: {err}"));
        let child = entry.path();
        if child.is_dir() {
            walk(&child, acc);
        } else if child.is_file() {
            acc.push(child);
        }
    }
}
