# evm-cloud Caddyfile — generated by Terraform, do not edit manually.
# Mode: ${ingress_mode} | Domain: ${domain}

# Catch-all: reject requests that bypass the configured domain
:80, :443 {
    respond "Forbidden" 403
}

${domain} {
%{ if ingress_mode == "cloudflare" ~}
    tls /etc/caddy/certs/origin.pem /etc/caddy/certs/origin-key.pem
%{ endif ~}
%{ if ingress_mode == "caddy" && tls_staging ~}
    tls ${tls_email} {
        ca https://acme-staging-v02.api.letsencrypt.org/directory
    }
%{ endif ~}
%{ if ingress_mode == "caddy" && !tls_staging ~}
    tls ${tls_email}
%{ endif ~}

    # Security headers
    header {
%{ if hsts_preload ~}
        Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
%{ else ~}
        Strict-Transport-Security "max-age=31536000; includeSubDomains"
%{ endif ~}
        X-Frame-Options "DENY"
        X-Content-Type-Options "nosniff"
        Referrer-Policy "strict-origin-when-cross-origin"
        Content-Security-Policy "default-src 'none'; frame-ancestors 'none'"
        -Server
    }

    request_body {
        max_size ${request_body_max_size}
    }

%{ if enable_rpc_proxy ~}
    reverse_proxy erpc:4000 {
%{ if ingress_mode == "cloudflare" ~}
        header_up X-Real-IP {http.request.header.CF-Connecting-IP}
        header_up X-Forwarded-For {http.request.header.CF-Connecting-IP}
%{ else ~}
        header_up X-Real-IP {remote_host}
        header_up X-Forwarded-For {remote_host}
%{ endif ~}
        header_up X-Forwarded-Proto {scheme}
    }
%{ endif ~}
}
