# Generated by evm-cloud v0.0.1-alpha8 builder
# https://app.evm-cloud.xyz
# Regenerate with the builder or use `evm-cloud init` to modify


# ──────────────────────────────────────────────────────────────────────
# Core
# ──────────────────────────────────────────────────────────────────────

project_name                        = "golden-test"
infrastructure_provider             = "bare_metal"
compute_engine                      = "docker_compose"
workload_mode                       = "terraform"
database_mode                       = "self_hosted"
secrets_mode                        = "inline"
deployment_target                   = "managed"
runtime_arch                        = "multi"

# ──────────────────────────────────────────────────────────────────────
# Bare Metal
# ──────────────────────────────────────────────────────────────────────

bare_metal_ssh_user                 = "ubuntu"
bare_metal_ssh_port                 = 22

# ──────────────────────────────────────────────────────────────────────
# Database
# ──────────────────────────────────────────────────────────────────────

indexer_storage_backend             = "clickhouse"
indexer_clickhouse_user             = "default"
indexer_clickhouse_db               = "rindexer"

# ──────────────────────────────────────────────────────────────────────
# Indexer / RPC Proxy
# ──────────────────────────────────────────────────────────────────────

rpc_proxy_enabled                   = true
indexer_enabled                     = true
indexer_rpc_url                     = ""
rpc_proxy_image                     = "ghcr.io/erpc/erpc:latest"
indexer_image                       = "ghcr.io/joshstevens19/rindexer:latest"

# Config content — populated by `evm-cloud init` from config/ files
erpc_config_yaml                    = ""
rindexer_config_yaml                = ""
rindexer_abis                       = {}
indexer_extra_env                   = {}

# ──────────────────────────────────────────────────────────────────────
# Ingress
# ──────────────────────────────────────────────────────────────────────

ingress_mode                        = "caddy"
erpc_hostname                       = "rpc.myvps.com"
ingress_tls_email                   = "admin@myvps.com"

# ──────────────────────────────────────────────────────────────────────
# Streaming
# ──────────────────────────────────────────────────────────────────────

streaming_mode                      = "disabled"