# Generated by evm-cloud v0.0.1-alpha8 builder
# https://app.evm-cloud.xyz
# Regenerate with the builder or use `evm-cloud init` to modify

output "workload_handoff" {
  description = "Deployment handoff data for external deployers"
  value       = module.evm_cloud.workload_handoff
  sensitive   = true
}
