/**
 * Pre-built example configurations — one per example/ directory.
 * These are selectable from the builder as "start from an example"
 * and also serve as import targets.
 */

import type { BuilderState, InfraProfile } from "./configSchema.ts";

export interface ExampleConfig {
  name: string;
  displayName: string;
  description: string;
  cost: string;
  state: Partial<BuilderState>;
}

export const EXAMPLES: ExampleConfig[] = [
  {
    name: "minimal_aws_byo_clickhouse",
    displayName: "AWS EC2 + ClickHouse",
    description: "Simplest AWS deployment — single EC2 with Docker, BYO ClickHouse.",
    cost: "~$15/mo",
    state: {
      projectName: "evm-cloud-ec2-ch",
      infraProfile: "aws_simple" as InfraProfile,
      provider: "aws",
      computeEngine: "ec2",
      workloadMode: "terraform",
      region: "us-east-1",
      instanceType: "t3.small",
      databaseProfile: "byodb_clickhouse",
      databaseName: "rindexer",
      chains: ["ethereum"],
      rpcEndpoints: { ethereum: "https://ethereum-rpc.publicnode.com" },
      ingressMode: "none",
      secretsMode: "inline",
    },
  },
  {
    name: "minimal_aws_rds",
    displayName: "AWS EC2 + Managed RDS",
    description: "EC2 with Docker + AWS managed PostgreSQL (RDS).",
    cost: "~$45/mo",
    state: {
      projectName: "evm-cloud-rds",
      infraProfile: "aws_simple" as InfraProfile,
      provider: "aws",
      computeEngine: "ec2",
      workloadMode: "terraform",
      region: "us-east-1",
      instanceType: "t3.small",
      databaseProfile: "managed_rds",
      databaseName: "rindexer",
      chains: ["ethereum"],
      rpcEndpoints: { ethereum: "https://ethereum-rpc.publicnode.com" },
      ingressMode: "none",
      secretsMode: "inline",
    },
  },
  {
    name: "minimal_aws_k3s_byo_clickhouse",
    displayName: "AWS k3s + ClickHouse",
    description: "Budget Kubernetes on AWS — k3s on EC2, BYO ClickHouse.",
    cost: "~$35/mo",
    state: {
      projectName: "evm-cloud-k3s",
      infraProfile: "aws_budget_k8s" as InfraProfile,
      provider: "aws",
      computeEngine: "k3s",
      workloadMode: "external",
      region: "us-east-1",
      instanceType: "t3.small",
      databaseProfile: "byodb_clickhouse",
      databaseName: "rindexer",
      chains: ["ethereum"],
      rpcEndpoints: { ethereum: "https://ethereum-rpc.publicnode.com" },
      ingressMode: "none",
      secretsMode: "inline",
    },
  },
  {
    name: "aws_k3s_cloudflare_ingress",
    displayName: "AWS k3s + Cloudflare",
    description: "k3s on AWS with Cloudflare TLS termination.",
    cost: "~$17/mo",
    state: {
      projectName: "evm-cloud-k3s-cf",
      infraProfile: "aws_budget_k8s" as InfraProfile,
      provider: "aws",
      computeEngine: "k3s",
      workloadMode: "external",
      region: "us-east-1",
      instanceType: "t3.small",
      databaseProfile: "byodb_clickhouse",
      databaseName: "rindexer",
      chains: ["ethereum"],
      rpcEndpoints: { ethereum: "https://ethereum-rpc.publicnode.com" },
      ingressMode: "cloudflare",
      secretsMode: "inline",
    },
  },
  {
    name: "aws_eks_BYO_clickhouse",
    displayName: "AWS EKS + ClickHouse",
    description: "Managed Kubernetes (EKS) with BYO ClickHouse.",
    cost: "~$110/mo",
    state: {
      projectName: "evm-cloud-eks-ch",
      infraProfile: "aws_managed_k8s" as InfraProfile,
      provider: "aws",
      computeEngine: "eks",
      workloadMode: "terraform",
      region: "us-east-1",
      instanceType: "t3.medium",
      databaseProfile: "byodb_clickhouse",
      databaseName: "rindexer",
      chains: ["ethereum"],
      rpcEndpoints: { ethereum: "https://ethereum-rpc.publicnode.com" },
      ingressMode: "none",
      secretsMode: "inline",
    },
  },
  {
    name: "minimal_aws_external_ec2_byo",
    displayName: "AWS EC2 External Deploy",
    description: "EC2 with external deployer — infra only, you deploy workloads.",
    cost: "~$15/mo",
    state: {
      projectName: "evm-cloud-external",
      infraProfile: "aws_simple" as InfraProfile,
      provider: "aws",
      computeEngine: "ec2",
      workloadMode: "external",
      region: "us-east-1",
      instanceType: "t3.micro",
      databaseProfile: "byodb_clickhouse",
      databaseName: "rindexer",
      chains: ["ethereum"],
      rpcEndpoints: { ethereum: "https://ethereum-rpc.publicnode.com" },
      ingressMode: "none",
      secretsMode: "inline",
    },
  },
  {
    name: "prod_aws_k3s_multi_byo_clickhouse",
    displayName: "Production k3s Multi-Node",
    description: "Production-grade: k3s multi-node, Cloudflare, Secrets Manager, monitoring.",
    cost: "~$40/mo",
    state: {
      projectName: "evm-cloud-prod",
      infraProfile: "aws_budget_k8s" as InfraProfile,
      provider: "aws",
      computeEngine: "k3s",
      workloadMode: "external",
      region: "us-east-1",
      instanceType: "c7i-flex.large",
      databaseProfile: "byodb_clickhouse",
      databaseName: "rindexer",
      chains: ["ethereum"],
      rpcEndpoints: { ethereum: "https://ethereum-rpc.publicnode.com" },
      ingressMode: "cloudflare",
      secretsMode: "provider",
      monitoring: { enabled: true, lokiEnabled: false, alertmanagerSlackChannel: "#alerts" },
    },
  },
  {
    name: "baremetal_byo_clickhouse",
    displayName: "VPS Docker + ClickHouse",
    description: "Any VPS with Docker Compose — cheapest option, BYO ClickHouse.",
    cost: "~$5/mo",
    state: {
      projectName: "evm-cloud-vps",
      infraProfile: "vps_docker" as InfraProfile,
      provider: "bare_metal",
      computeEngine: "docker_compose",
      workloadMode: "terraform",
      region: "",
      instanceType: "",
      databaseProfile: "byodb_clickhouse",
      databaseName: "rindexer",
      chains: ["ethereum"],
      rpcEndpoints: { ethereum: "https://ethereum-rpc.publicnode.com" },
      ingressMode: "none",
      secretsMode: "inline",
    },
  },
  {
    name: "baremetal_k3s_byo_db",
    displayName: "VPS k3s + PostgreSQL",
    description: "k3s on bare metal with BYO PostgreSQL.",
    cost: "VPS cost",
    state: {
      projectName: "evm-cloud-bm-k3s",
      infraProfile: "vps_k8s" as InfraProfile,
      provider: "bare_metal",
      computeEngine: "k3s",
      workloadMode: "external",
      region: "",
      instanceType: "",
      databaseProfile: "byodb_postgres",
      databaseName: "rindexer",
      chains: ["ethereum"],
      rpcEndpoints: { ethereum: "https://ethereum-rpc.publicnode.com" },
      ingressMode: "none",
      secretsMode: "inline",
    },
  },
  {
    name: "baremetal_defi_k3s_with_api",
    displayName: "DeFi k3s + Custom API",
    description: "Bare metal k3s with Cloudflare + custom swap API service.",
    cost: "VPS cost",
    state: {
      projectName: "defi-swaps",
      infraProfile: "vps_k8s" as InfraProfile,
      provider: "bare_metal",
      computeEngine: "k3s",
      workloadMode: "external",
      region: "",
      instanceType: "",
      databaseProfile: "byodb_clickhouse",
      databaseName: "rindexer",
      chains: ["ethereum"],
      rpcEndpoints: { ethereum: "https://ethereum-rpc.publicnode.com" },
      ingressMode: "cloudflare",
      secretsMode: "inline",
    },
  },
];
