/**
 * TypeScript port of cli/src/init_templates/config.rs::render_evm_cloud_toml()
 *
 * Generates evm-cloud.toml from BuilderState.
 * Output must match CLI format character-for-character.
 *
 * IMPORTANT: Schema contract test (M1) verifies parity with Rust output.
 */

import {
  type BuilderState,
  BUILDER_VERSION,
  BUILDER_MODULE_VERSION,
} from "./configSchema.ts";

/** Infer storage_backend from database profile */
function inferStorageBackend(profile: string): string {
  if (profile.includes("clickhouse")) return "clickhouse";
  return "postgres";
}

/** Infer database mode from profile */
function inferDatabaseMode(profile: string): string {
  if (profile.startsWith("managed")) return "managed";
  return "self_hosted";
}

export function generateToml(state: BuilderState): string {
  const lines: string[] = [];

  lines.push(`# Generated by evm-cloud builder v${BUILDER_VERSION} (module v${BUILDER_MODULE_VERSION})`);
  lines.push(`# https://app.evm-cloud.xyz/builder`);
  lines.push(`# Regenerate with the builder or use \`evm-cloud init\` to modify`);
  lines.push("");
  lines.push("schema_version = 1");
  lines.push("");

  // [project]
  lines.push("[project]");
  lines.push(`name = "${state.projectName}"`);
  if (state.provider === "aws" && state.region) {
    lines.push(`region = "${state.region}"`);
  }
  lines.push("");

  // [compute]
  lines.push("[compute]");
  lines.push(`engine = "${state.computeEngine}"`);
  if (state.provider === "aws" && state.instanceType) {
    lines.push(`instance_type = "${state.instanceType}"`);
  }
  lines.push("");

  // [database]
  lines.push("[database]");
  lines.push(`mode = "${inferDatabaseMode(state.databaseProfile)}"`);
  lines.push(`provider = "${state.provider}"`);
  lines.push(`storage_backend = "${inferStorageBackend(state.databaseProfile)}"`);
  lines.push("");

  // [indexer]
  lines.push("[indexer]");
  if (state.indexerType !== "rindexer") {
    lines.push(`indexer_type = "${state.indexerType}"`);
  }
  lines.push(`config_path = "config/rindexer.yaml"`);
  if (state.chains.some(() => true)) {
    lines.push(`erpc_config_path = "config/erpc.yaml"`);
  }
  lines.push(`chains = [${state.chains.map((c) => `"${c}"`).join(", ")}]`);
  if (Object.keys(state.extraEnv).length > 0) {
    lines.push("");
    lines.push("[indexer.extra_env]");
    for (const [key, value] of Object.entries(state.extraEnv)) {
      lines.push(`${key} = "${value}"`);
    }
  }
  lines.push("");

  // [rpc]
  lines.push("[rpc.endpoints]");
  for (const chain of state.chains) {
    const url = state.rpcEndpoints[chain] || "";
    lines.push(`${chain} = "${url}"`);
  }
  lines.push("");

  // [ingress]
  lines.push("[ingress]");
  lines.push(`mode = "${state.ingressMode}"`);
  if (state.ingressMode !== "none" && state.domain) {
    lines.push(`domain = "${state.domain}"`);
  }
  if (
    (state.ingressMode === "caddy" || state.ingressMode === "ingress_nginx") &&
    state.tlsEmail
  ) {
    lines.push(`tls_email = "${state.tlsEmail}"`);
  }
  lines.push("");

  // [secrets]
  lines.push("[secrets]");
  lines.push(`mode = "${state.secretsMode}"`);
  lines.push("");

  // Optional sections

  // [monitoring]
  if (state.monitoring?.enabled) {
    lines.push("[monitoring]");
    lines.push("enabled = true");
    if (state.monitoring.grafanaHostname) {
      lines.push(`grafana_hostname = "${state.monitoring.grafanaHostname}"`);
    }
    if (state.monitoring.lokiEnabled) {
      lines.push("loki_enabled = true");
    }
    lines.push("");
  }

  // [streaming]
  if (state.streaming && state.streaming.mode !== "disabled") {
    lines.push("[streaming]");
    lines.push(`mode = "${state.streaming.mode}"`);
    lines.push("");
  }

  // [networking]
  if (state.networking) {
    lines.push("[networking]");
    if (state.networking.vpcCidr) {
      lines.push(`vpc_cidr = "${state.networking.vpcCidr}"`);
    }
    if (state.networking.enableVpcEndpoints != null) {
      lines.push(`enable_vpc_endpoints = ${state.networking.enableVpcEndpoints}`);
    }
    if (state.networking.environment) {
      lines.push(`environment = "${state.networking.environment}"`);
    }
    lines.push("");
  }

  // [state]
  if (state.stateBackend) {
    if (state.stateBackend.backend === "s3") {
      lines.push("[state]");
      lines.push(`backend = "s3"`);
      lines.push(`bucket = "${state.stateBackend.bucket}"`);
      lines.push(`dynamodb_table = "${state.stateBackend.dynamodbTable}"`);
      lines.push(`region = "${state.stateBackend.region}"`);
      if (state.stateBackend.key) {
        lines.push(`key = "${state.stateBackend.key}"`);
      }
      lines.push(`encrypt = ${state.stateBackend.encrypt}`);
    } else {
      lines.push("[state]");
      lines.push(`backend = "gcs"`);
      lines.push(`bucket = "${state.stateBackend.bucket}"`);
      lines.push(`region = "${state.stateBackend.region}"`);
      if (state.stateBackend.prefix) {
        lines.push(`prefix = "${state.stateBackend.prefix}"`);
      }
    }
    lines.push("");
  }

  return lines.join("\n");
}
