/**
 * Client-side zip generation using JSZip.
 * Assembles all generated files into a downloadable project scaffold.
 */

import JSZip from "jszip";
import type { BuilderState } from "./configSchema.ts";
import { generateToml } from "./tomlGenerator.ts";
import {
  generateVersionsTf,
  generateMainTf,
  generateVariablesTf,
  generateOutputsTf,
  generateTfvarsJson,
  generateSecretsExample,
  generateTfBackend,
  generateGitignore,
  generateMakefile,
  generateMetadata,
  generateReadme,
} from "./tfGenerator.ts";

export async function exportZip(state: BuilderState): Promise<void> {
  const zip = new JSZip();
  const root = zip.folder(state.projectName)!;

  // ── evm-cloud.toml ────────────────────────────────────────────────────
  root.file("evm-cloud.toml", generateToml(state));

  // ── Terraform scaffold ────────────────────────────────────────────────
  root.file("versions.tf", generateVersionsTf(state));
  root.file("main.tf", generateMainTf(state));
  root.file("variables.tf", generateVariablesTf(state));
  root.file("outputs.tf", generateOutputsTf());
  root.file("terraform.auto.tfvars", generateTfvarsJson(state));

  // Secrets example (only if there are sensitive vars)
  const secretsExample = generateSecretsExample(state);
  if (secretsExample) {
    root.file("secrets.auto.tfvars.example", secretsExample);
  }

  // Backend config (only if remote state configured)
  const tfBackend = generateTfBackend(state);
  if (tfBackend && state.stateBackend) {
    const filename = `${state.projectName}.${state.stateBackend.backend}.tfbackend`;
    root.file(filename, tfBackend);
  }

  // ── Config files ──────────────────────────────────────────────────────
  const config = root.folder("config")!;

  // Placeholder rindexer.yaml + erpc.yaml
  // TODO: replace with full generators (rindexerGenerator.ts, erpcGenerator.ts)
  config.file("rindexer.yaml", generatePlaceholderRindexerYaml(state));
  config.file("erpc.yaml", generatePlaceholderErpcYaml(state));

  // ABIs directory (empty placeholder — templates will populate this)
  config.folder("abis");

  // ── Project files ─────────────────────────────────────────────────────
  root.file(".gitignore", generateGitignore());
  root.file("Makefile", generateMakefile());
  root.file(".evm-cloud.json", generateMetadata(state));
  root.file("README.md", generateReadme(state));

  // ── Generate blob and trigger download ────────────────────────────────
  const blob = await zip.generateAsync({ type: "blob" });
  downloadBlob(blob, `${state.projectName}.zip`);
}

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ── Config generators (placeholder — until full generators land) ──────

export function generatePlaceholderRindexerYaml(state: BuilderState): string {
  const dbName = state.databaseName || "rindexer";
  const lines: string[] = [];
  lines.push("name: " + dbName);
  lines.push("description: Generated by evm-cloud builder");
  lines.push("repository: https://github.com/joshstevens19/rindexer");
  lines.push("");
  lines.push("networks:");

  for (const chain of state.chains) {
    const rpc = state.rpcEndpoints[chain] || "${RPC_URL}";
    lines.push(`  - name: ${chain}`);
    lines.push(`    chain_id: ${getChainId(chain)}`);
    lines.push(`    rpc: ${rpc}`);
  }

  lines.push("");
  lines.push("# Add your contract definitions below");
  lines.push("# See: https://rindexer.xyz/docs/start/yaml-config");
  lines.push("contracts: []");

  return lines.join("\n");
}

export function generatePlaceholderErpcYaml(state: BuilderState): string {
  const lines: string[] = [];
  lines.push("logLevel: warn");
  lines.push("");
  lines.push("server:");
  lines.push("  httpHostV4: 0.0.0.0");
  lines.push("  httpPort: 4000");
  lines.push("");
  lines.push("projects:");
  lines.push("  - id: main");
  lines.push("    networks:");

  for (const chain of state.chains) {
    const chainId = getChainId(chain);
    lines.push(`      - architecture: evm`);
    lines.push(`        evm:`);
    lines.push(`          chainId: ${chainId}`);
    lines.push(`        failsafe:`);
    lines.push(`          retry:`);
    lines.push(`            maxAttempts: 5`);
    lines.push(`            delay: 500ms`);
    lines.push(`            backoffMaxDelay: 10s`);
    lines.push(`            backoffFactor: 2`);
    lines.push(`          timeout:`);
    lines.push(`            duration: 30s`);
  }

  lines.push("    upstreams:");
  lines.push("      - id: evm-public");
  lines.push("        endpoint: repository://evm-public-endpoints.erpc.cloud");
  lines.push("        type: evm");

  // User-provided RPCs as additional upstreams
  for (const chain of state.chains) {
    const rpc = state.rpcEndpoints[chain];
    if (rpc) {
      lines.push(`      - id: ${chain}-custom`);
      lines.push(`        endpoint: ${rpc}`);
      lines.push(`        type: evm`);
    }
  }

  return lines.join("\n");
}

function getChainId(chain: string): number {
  const ids: Record<string, number> = {
    ethereum: 1,
    polygon: 137,
    arbitrum: 42161,
    base: 8453,
    optimism: 10,
    hyperliquid: 999,
  };
  return ids[chain] ?? 1;
}
