apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "indexer.fullname" . }}-abis
  labels:
    app.kubernetes.io/name: {{ include "indexer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
{{- if .Values.config.abis }}
{{ toYaml .Values.config.abis | indent 2 }}
{{- else }}
  .keep: "{}"
{{- end }}
