apiVersion: v1
kind: Service
metadata:
  name: {{ include "anvil.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "anvil.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "anvil.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: rpc
      port: {{ .Values.service.port }}
      targetPort: rpc
      protocol: TCP
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
